### ISSUE TITLE
Actually There Is a Motivation to Fight It

### ISSUE THREAD

**Issue by nikitaeverywhere** [Qix-/tabs-are-better-than-spaces#3]
Tabs are awesome for code indentation, I agree. They fit to the *reader's* style good. However, there are *at least two* cases "which you cannot fight against":

1.1. If we will talk about which one we have to get rid of, spaces or tabs, the answer is obvious — we cannot get rid of spaces. ([Quote](https://youtu.be/NPB34lDZj3E?t=587))
1.2. If you use "responsive" tabs for indentation, you will not be able to control alignment as you might want to. Some of the examples:

```javascript
let variable1 = 1,
    variable2 = 2,
    variable3 = 3;
```

Don't use `,` while declaring variables? What about HTML:

```html
<div>
    <div class="class1 class2 class3"
         attr1="value1"
         attr2="value2"
         attr3="value3">
        ...
    </div>
</div>
```

1.3. Do you keep the max line width of `100` characters (for example)? If you use tabs, its impossible to answer "yes" here.

From the other side, when using spaces,

2.1. You cannot dynamically adjust indentations to fit the *reader's* eye. That's all. But does *reading* the code indented with tabs on GitHub (or any other Internet resource) fits your eye? (GitHub's code is indented with exactly `8` spaces, when no [such tools](https://github.com/sindresorhus/refined-github) installed)

Did I miss something? It would be nice to hear the motivation to use tabs instead of spaces stronger than this! Thank you!

**Comment by Qix-** [comment]
Hey, great questions :)

1.1. He masks his opinion as fact - I don't see how anything he said was true. We don't have to get "rid of" either one of them so long as the language designers don't care. Since they're not a semantic element of just about any language (obvious exceptions are Python and YAML), there's absolutely no reason why they can't be skipped over in the lexer just like spaces are.

For those cases, while tabs are allowed in Python specifically (but not YAML), it's pretty obvious which one you have to use. Tab users aren't opposed to using spaces when it's a requirement (I think I speak for most when I say that).

1.2. I'm not sure what the argument is here. [Here is your code thrown into the demo](https://tabs.now.sh/#/qix-/tabs-are-better-than-spaces/master/examples/multiline-html.htm).

1.3. No :) Max line widths are an archaic requirement and I've personally ditched them for almost a year now. I've never, ever had an issue where I've thought "Man, I wish this code was really compacted". Soft line wrapping occurs sometimes, but when you choose to break a statement into two lines, it no longer becomes a requirement of character, but of practicality - which ultimately makes your code much nicer to look at anyway.

2.1. I agree that Github's default 8 spaces for tabs is a bit much, but that's not necessarily Github's fault - the default for _most_ browsers is 8 space tab-widths. However, Github should be adding the CSS property `tab-size: 4` property as a sane default IMO.

---

The only real advice I can give to someone that is using spaces for indentation is to try tabs for their next project. If you're a javascript developer, adhere to the [XO standard](https://github.com/sindresorhus/xo) by running it in your `test` or `pretest` script. If you follow the *Tabs for Indentation, Spaces for Alignment* mantra, you really can't go wrong.

Just try it for a bit and see which one you think is superior. Also remember to set a tab-width that is right for you (since you now have the option to do so without affecting other developers).

**Comment by nikitaeverywhere** [comment]
> 1.2. I'm not sure what the argument is here. Here is your code thrown into the demo..

Wow, I'm surprised that you mixed spaces and tabs. And this worked in a really beautiful way.

Thanks for the suggestions! Now I feel more optimistic about tabs :)

There is one thing I want to feel like this either. A single quote character. Why people like to use them? Because they are so lazy to press "Shift"? (If they are, why aren't they lazy to press tabs and spaces instead of just spaces?) To be honest, I see that there is no matter what to use `"When I want to \"quote\" some word"` or `'when it\'s time for apostrophe'`. But personally, I prefer `"` just because it feels more natural. Open Microsoft Word or Google Docs, quote some string, and you will see double quote there, and there is a normal, historical reason for it.

**Comment by Qix-** [comment]
@ZitRos That one is more preference. There are only a few languages where the distinction doesn't have a semantic difference. Otherwise, the double/single thing _does_ make a difference:

```shell
# foo.sh
FOO="Hello"
echo "$FOO" # outputs "Hello"
echo '$FOO' # outputs "$FOO"
```

```c
// foo.c
puts("Hello!"); // outputs "Hello!"
puts('Hello!'); // compilation error
```

It's not a matter of laziness, but holding shift _does_ slow you down. In fact, "laziness" is usually directly proportional to quickness when writing code. I personally don't have strong opinions (as I do a lot of code in C, so they don't bother me as much).

Though in Javascript, I will agree that they look cleaner. Maybe @sindresorhus has some ideas as to why the XO standard in particular favors single quotes over double.

**Comment by nikitaeverywhere** [comment]
Nice, thank you! Special thanks for the nice demo. And congrats on getting a number-only commit hash of 2193775bb494ec3f1732241fb9db6808d57a09a4 (~3.72% probability) :)

**Comment by sindresorhus** [comment]
I find single-quotes less noisy. One line instead of two. And it's easier to type.

**Comment by nikitaeverywhere** [comment]
> And it's easier to type.

I think the ease (and speed) of typing is a matter of habit. If you get used to type `'`, then it's faster. For those like me, who have multiple keyboard layouts (I have 3) pressing Shift is never the issue :smile:

Regarding to noisiness of `"`, I can say that possibly I get used to such string quotations when reading texts. Which is usual. Still, `'` associates more like apostrophe than quotation.

But I agree it's all about preference and special thanks @Sindresorhus for giving an option to choose from in [XO](https://github.com/sindresorhus/xo)!
